-- MySQL Script generated by MySQL Workbench
-- Mon Apr  3 21:14:29 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`download`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`download` (
  `download_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `download_date` VARCHAR(45) NOT NULL,
  `product_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`download_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`product` (
  `product_id` INT NOT NULL,
  `product_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`product_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `user_id` INT NOT NULL,
  `email_address` VARCHAR(45) NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `product_product_id` INT NOT NULL,
  PRIMARY KEY (`user_id`),
  INDEX `fk_user_download_idx` (`email_address` ASC) VISIBLE,
  INDEX `fk_user_product1_idx` (`product_product_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_download`
    FOREIGN KEY (`email_address`)
    REFERENCES `mydb`.`download` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_product1`
    FOREIGN KEY (`product_product_id`)
    REFERENCES `mydb`.`product` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`product_has_download`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`product_has_download` (
  `product_product_id` INT NOT NULL,
  `download_download_id` INT NOT NULL,
  PRIMARY KEY (`product_product_id`, `download_download_id`),
  INDEX `fk_product_has_download_download1_idx` (`download_download_id` ASC) VISIBLE,
  INDEX `fk_product_has_download_product1_idx` (`product_product_id` ASC) VISIBLE,
  CONSTRAINT `fk_product_has_download_product1`
    FOREIGN KEY (`product_product_id`)
    REFERENCES `mydb`.`product` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_has_download_download1`
    FOREIGN KEY (`download_download_id`)
    REFERENCES `mydb`.`download` (`download_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
