-- MySQL Script generated by MySQL Workbench
-- Thu Nov  3 22:55:49 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema MediCareDiagram
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema MediCareDiagram
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `MediCareDiagram` DEFAULT CHARACTER SET utf8 ;
USE `MediCareDiagram` ;

-- -----------------------------------------------------
-- Table `MediCareDiagram`.`Insurance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MediCareDiagram`.`Insurance` (
  `idInsurance` INT NOT NULL,
  `membershipType` VARCHAR(45) NULL,
  PRIMARY KEY (`idInsurance`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MediCareDiagram`.`Patient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MediCareDiagram`.`Patient` (
  `idPatient` INT NOT NULL,
  `firstName` VARCHAR(45) NULL,
  `lastName` VARCHAR(45) NULL,
  `reasonForVisit` VARCHAR(45) NULL,
  `insuranceIdNumber` INT NULL,
  `Insurance_idInsurance` INT NOT NULL,
  PRIMARY KEY (`idPatient`),
  INDEX `fk_Patient_Insurance1_idx` (`Insurance_idInsurance` ASC) VISIBLE,
  CONSTRAINT `fk_Patient_Insurance1`
    FOREIGN KEY (`Insurance_idInsurance`)
    REFERENCES `MediCareDiagram`.`Insurance` (`idInsurance`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MediCareDiagram`.`HealthCareProvider`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MediCareDiagram`.`HealthCareProvider` (
  `idHealthCareProvider` INT NOT NULL,
  `departmentId` INT NULL,
  `Patient_idPatient` INT NOT NULL,
  `Insurance_idInsurance` INT NOT NULL,
  PRIMARY KEY (`idHealthCareProvider`),
  INDEX `fk_HealthCareProvider_Patient_idx` (`Patient_idPatient` ASC) VISIBLE,
  INDEX `fk_HealthCareProvider_Insurance1_idx` (`Insurance_idInsurance` ASC) VISIBLE,
  CONSTRAINT `fk_HealthCareProvider_Patient`
    FOREIGN KEY (`Patient_idPatient`)
    REFERENCES `MediCareDiagram`.`Patient` (`idPatient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_HealthCareProvider_Insurance1`
    FOREIGN KEY (`Insurance_idInsurance`)
    REFERENCES `MediCareDiagram`.`Insurance` (`idInsurance`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
